### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-sandrusmb#1]
Buen trabajo @sandrusmb!

### Algunas pistas para acabarlo:

- [x] Estas props no existen https://github.com/Adalab/modulo-3-evaluacion-intermedia-sandrusmb/blob/master/src/components/PokemonList.js#L9-L10
- [x] Arregla el paso de props para que se muestre la imagen https://github.com/Adalab/modulo-3-evaluacion-intermedia-sandrusmb/blob/master/src/components/Pokemon.js#L7
- [x] Usa el estado para guardar los datos.
- [x] Usa el `id` de cada pokemon para el `key` de react cuando mapeas y creas un listado de componentes https://github.com/Adalab/modulo-3-evaluacion-intermedia-sandrusmb/blob/master/src/components/App.js#L14
- [x] Añade estilos (un archivo sass o css por componente)
- [ ] Usa propTypes para comprobar el tipo de dato de las props
- [ ] Revisa los metadatos en index.html (lang, title...)
- [x] Debemos iterar con un map, también los tipos https://github.com/Adalab/modulo-3-evaluacion-intermedia-sandrusmb/blob/master/src/components/Pokemon.js#L9

### Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by sandrusmb** [comment]
Hola @migueldelmazo, 

He revisado el proyecto de la evaluación intermedia. Así es como ha quedado finalmente: http://beta.adalab.es/modulo-3-evaluacion-intermedia-sandrusmb/

Gracias. Un saludo.
